---
apiVersion: v2
name: tracing-es-jaeger
version: 0.0.1
dependencies:
  - name: elasticsearch
    condition: elasticsearch.enabled
    version: 7.17.3
    repository: https://helm.elastic.co
  - name: jaeger
    condition: jaeger.enabled
    version: ^0.62.1
    repository: https://jaegertracing.github.io/helm-charts
