tobs:
  enabled: true
  namespaceOverride: ""
  timescaledb-single:
    enabled: &dbEnabled true
    image:
      repository: timescale/timescaledb-ha
      tag: pg14.5-ts2.8.0-p1
      pullPolicy: IfNotPresent
    env:
      - name: TSTUNE_PROFILE
        value: promscale
    loadBalancer:
      enabled: false
    replicaCount: 1
    backup:
      enabled: false
    persistentVolumes:
      data:
        size: 150Gi
      wal:
        size: 20Gi
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
    prometheus:
      enabled: true
      image:
        repository: quay.io/prometheuscommunity/postgres-exporter
        tag: v0.11.1
    podMonitor:
      enabled: true
  promscale:
    enabled: true
    image:
      repository: timescale/promscale
      tag: 0.14.0
      pullPolicy: IfNotPresent
    extraArgs:
      - "--metrics.high-availability=false"
    extraEnv:
      - name: "TOBS_TELEMETRY_INSTALLED_BY"
        value: "helm"
      - name: "TOBS_TELEMETRY_VERSION"
        value: "{{ .Chart.Version }}"
      - name: "TOBS_TELEMETRY_TRACING_ENABLED"
        value: "true"
      - name: "TOBS_TELEMETRY_TIMESCALEDB_ENABLED"
        value: *dbEnabled
    serviceMonitor:
      enabled: true
    connectionSecretName: "tobs-promscale-connection"
    resources:
      requests:
        memory: 500Mi
        cpu: 30m
  kube-prometheus-stack:
    enabled: true
    defaultRules:
      rules:
        etcd: false
        kubeControllerManager: false
        kubeProxy: false
        kubeScheduler: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    alertmanager:
      enabled: false
    prometheusOperator:
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.59.2
        pullPolicy: IfNotPresent
      prometheusConfigReloader:
        image:
          repository: quay.io/prometheus-operator/prometheus-config-reloader
          tag: v0.59.2
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 50Mi
      resources:
        limits:
          memory: 200Mi
          cpu: 100m
        requests:
          memory: 100Mi
          cpu: 10m
    prometheus:
      prometheusSpec:
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.38.0
        scrapeInterval: "1m"
        scrapeTimeout: "10s"
        evaluationInterval: "1m"
        retention: 5d
        remoteRead: []
        remoteWrite: []
        replicas: 1
        resources:
          requests:
            memory: 400Mi
            cpu: 40m
        storageSpec:
          disableMountSubPath: true
          volumeClaimTemplate:
            spec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 8Gi
        additionalScrapeConfigsSecret:
          enabled: true
          name: tobs-scrape-config
          key: additional-scrape-config.yaml
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 9.1.6
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 50m
          memory: 250Mi
      envValueFrom:
        GRAFANA_PASSWORD:
      sidecar:
        datasources:
          enabled: true
          defaultDatasourceEnabled: false
        dashboards:
          multicluster:
            global:
              enabled: false
          enabled: true
          files:
            - dashboards/promscale.json
      adminUser: admin
      adminPassword: ""
      persistence:
        type: pvc
        enabled: true
        accessModes:
          - ReadWriteOnce
      prometheus:
        datasource:
          enabled: true
          url: "http://{{ .Release.Name }}-kube-prometheus-stack-prometheus.{{ .Release.Namespace }}.svc:9090"
      timescale:
        datasource:
          enabled: false
    kube-state-metrics:
      image:
        repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
        tag: v2.6.0
        pullPolicy: IfNotPresent
      prometheusScrape: false
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 30Mi
    prometheus-node-exporter:
      image:
        repository: quay.io/prometheus/node-exporter
        tag: v1.3.1
        pullPolicy: IfNotPresent
      service:
        annotations:
          prometheus.io/scrape: "false"
      resources:
        limits:
          cpu: 250m
          memory: 180Mi
        requests:
          cpu: 30m
          memory: 50Mi
  opentelemetry-operator:
    enabled: false
avalanche:
  enabled: true
  image:
    repository: quay.io/prometheuscommunity/avalanche
    tag: main
    pullPolicy: Always
  replicaCount: 1
  extraArgs:
    - --metric-count=100
    - --label-count=10
    - --series-count=10
    - --const-label=cluster=avalanche
    - --const-label=replica=0
    - --value-interval=60
    - --series-interval=315360000
    - --metric-interval=315360000
    - --remote-batch-size=2500
    - --remote-requests-count=1000000
    - --remote-write-interval=30s
    - --remote-url=http://{{ .Release.Name }}-promscale.{{ .Release.Namespace }}.svc:9201/write
  annotations: {}
  podAnnotations: {}
  serviceMonitor:
    enabled: false
  service:
    type: "ClusterIP"
    annotations: {}
    port: 9001
    spec: {}
  serviceAccount:
    create: true
  resources: {}
  readinessProbe: {}
