timescaledb-single:
  enabled: true
  replicaCount: 1
  backup:
    enabled: false
  persistentVolumes:
    data:
      size: 150Gi
      storageClass: gp3
    wal:
      size: 50Gi
      storageClass: gp3
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            checkpoint_timeout: 15min
            bgwriter_delay: 200ms
            bgwriter_lru_maxpages: 0
            bgwriter_lru_multiplier: 1
            stats_temp_directory: /tmp/pg_stat_temp
            # timescaledb.max_open_chunks_per_insert: 429
  resources:
    requests:
      cpu: "8"
      memory: 32Gi
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - connector
          topologyKey: "kubernetes.io/hostname"

promscale:
  enabled: true
  # If you want to use a different image, you can do so here.
  image:
    repository: timescale/promscale
  #   tag: 0.14.0
    pullPolicy: IfNotPresent
  extraArgs:
    - "--metrics.high-availability=false"
  connectionSecretName: "tobs-promscale-connection"
  resources:
    requests:
      memory: 16Gi
      cpu: "4"
  config:
    startup.dataset.config: |
      metrics:
        default_chunk_interval: 1h
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - timescaledb
          topologyKey: "kubernetes.io/hostname"

kube-prometheus-stack:
  enabled: true
  defaultRules:
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false
      kubeScheduler: false
  kubeControllerManager:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  alertmanager:
    enabled: false
  prometheusOperator:
    admissionWebhooks:
      enabled: true
  # This prometheus is monitoring the cluster. Do not use it for load generation.
  prometheus:
    prometheusSpec:
      remoteWriteDashboards: true
      remoteRead: []
      remoteWrite: []
      retention: 25d
      replicas: 1
      additionalScrapeConfigsSecret:
        enabled: false
      ruleNamespaceSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorNamespaceSelector: {}
      probeNamespaceSelector: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - timescaledb
              topologyKey: "kubernetes.io/hostname"
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - connector
              topologyKey: "kubernetes.io/hostname"
  grafana:
    enabled: true
    service:
      type: LoadBalancer
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Editor"
    envValueFrom:
      GRAFANA_PASSWORD:
    prometheus:
      datasource:
        enabled: true
        url: "http://{{ .Release.Name }}-kube-prometheus-stack-prometheus.{{ .Release.Namespace }}.svc:9090"
    timescale:
      datasource:
        enabled: false
opentelemetry-operator:
  enabled: false
