microsimReplicas: 1
microsimWorkers: 3
microsimTestDuration: "10m"
microsimSleepDuration: "100ms"
microsimCollector: "http://microsim-jaeger-collector.microsim.svc:14268/api/traces"
# To use the OTEL collector enabled below and set the microsimCollector to
# microsimCollector: "http://microsim-opentelemetry-collector.microsim.svc:14268/api/traces"

jaeger:
  tag: "1.38.1"
  provisionDataStore:
    cassandra: false
  storage:
    type: grpc-plugin
    grpcPlugin:
      extraEnv:
        - name: GRPC_STORAGE_SERVER
          value: "tobs-promscale.bench.svc:9202"
  agent:
    enabled: false
  collector:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: tobs
  agentSidecar:
    enabled: false
  query:
    agentSidecar:
      enabled: false

opentelemetry-collector:
  enabled: false
  mode: deployment
  serviceMonitor:
    enabled: true
    extraLabels:
      release: tobs
  config:
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_http:
      otlp:
        protocols:
          grpc:
          http:
      prometheus: null
      zipkin: null
    exporters:
      logging:
      otlp:
        endpoint: "tobs-promscale.bench.svc:9202"
        tls:
          insecure: true
        sending_queue:
          queue_size: 1000000
        timeout: 10s
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          exporters: [otlp]
          processors: [batch]
