apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: ingest-with-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-prometheus-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-prometheus-sa
  namespace: {{ .Release.Namespace }}
