prometheus:
  version: v2.39.1
  # Configuration options in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RemoteWriteSpec
  remoteWrite:
  - url: http://tobs-promscale.bench.svc:9201/write
    remoteTimeout: 100s
    # Configuration options in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#queueconfig
    queueConfig:
      capacity: 100000
      minShards: 20
      maxShards: 20
      maxSamplesPerSend: 10000
      batchSendDeadline: 30s
      minBackoff: 100ms
      maxBackoff: 10s
  resources:
    requests:
      cpu: 40m
      memory: 400Mi

# TODO: add querier configuation options
# querier:
