image:
  repository: quay.io/prometheuscommunity/avalanche
  tag: main
  pullPolicy: Always
replicaCount: 1
labels:
  tobs/excluded: "true"
extraArgs:
  - --const-label=avalanche_replica=$(POD_NAME)
  - --metric-count=100
  - --label-count=10
  - --series-count=10
  - --const-label=cluster=avalanche
  - --const-label=replica=0
  - --value-interval=60
  - --series-interval=315360000
  - --metric-interval=315360000
  - --remote-batch-size=2500
  - --remote-requests-count=1000000
  - --remote-write-interval=30s
  - --remote-url=http://tobs-promscale.bench.svc:9201/write
